### PR TITLE
Overhaul thruster code & impl cc for thrusters

### LINKED ISSUE #13: Thrusters ignore redstone power from block
**BEFORE REPORTING MAKE SURE:**
- [x] You are on the newest version of Starlance and Valkyrien Skies.
- [ ] You have tested it with only Starlance, Valkyrien Skies and Kotlin for Forge installed.
- [x] The bug hasn't been reported already.

**Describe the bug**
thrusters can only use vanilla redstone powers. but does cannot use redstone power come from CC:T

**To Reproduce**
1. place a computer
2. place a thruster next to the computer
3. let computer emit redstone
4. the thruster does not work

**Expected behavior**
The thruster should work with the power the computer provides

**Screenshots/videos**

https://github.com/user-attachments/assets/cd5a724d-5cba-4455-b5e4-81f94e4e685d

https://github.com/user-attachments/assets/045a03e3-d2a0-4cdd-aba5-afb2fa44bbcb

**Logs**
*The game logs: latest.log, crash report (if exists). Please don't just paste it here. Upload the file or use a site like pastebin*
[latest.log](https://github.com/user-attachments/files/18384155/latest.log)

**Versions**
 - Starlance version: 1.2.0
 - Valkrien Skies version: 120-2.3.0-beta.5

**Additional context**
*Anything else*

### PR DESCRIPTION
**Pull request by zyxkad**
fix #13 
impl cc peripheral on thrusters

### CODE REVIEW

**Comment by zyxkad** [comment]
https://github.com/user-attachments/assets/da4e30b7-644c-42d4-bcf5-17ac22062fa7

Particle still have render bug tho, I don't think that's something I can fix easily

File: src/main/java/net/jcm/vsch/compat/computer/ThrusterPeripheral.java [hunk 1]
```diff
@@ -0,0 +1,74 @@
...
+	}
+
+	@Override
+	public Object getTarget() {
+		return this.entity;
+	}
+
+	@Override
+	public String getType() {
+		return "thruster";
```
Comment (zyxkad) [inline src/main/java/net/jcm/vsch/compat/computer/ThrusterPeripheral.java:22]: I wonder if this simple name will conflict with other mods

Comment (blockninja124) [reply src/main/java/net/jcm/vsch/compat/computer/ThrusterPeripheral.java:22]: hm possibly, maybe we should change it to starlance_thruster.

**Comment by blockninja124** [comment]
The particle rendering I think is probably cosmic horizons issue, so not much we can do about it. It does the same with nodules

**Comment by blockninja124** [comment]
is this branch ready to merge? I saw on the discord you were still having some issues.

**Comment by jcm236** [comment]
Particle rendering is just forge culling it I suppose

**Comment by zyxkad** [comment]
> is this branch ready to merge? I saw on the discord you were still having some issues.

Yeah it's ready. unless you want me solve all the bugs and complete whole Starlance here...

**Comment by zyxkad** [comment]
But wait, I forgot setMode/getMode

**Comment by blockninja124** [comment]
Aha so it wasn't quite ready :D 

Anyway I'll just take a quick look and then we can probably merge

File: src/main/java/net/jcm/vsch/blocks/custom/DragInducerBlock.java [hunk 2]
```diff
@@ -119,11 +119,11 @@ public InteractionResult use(BlockState state, Level level, BlockPos pos, Player
 						if (data.mode == ThrusterData.ThrusterMode.POSITION) {
 							data.mode = ThrusterData.ThrusterMode.GLOBAL;
 							//TODO: Find a way to change this message if the last message was the same (so it looks like a new message)
-							player.displayClientMessage(Component.literal("Set thruster to GLOBAL").withStyle(ChatFormatting.GOLD), true);
```
Comment (blockninja124) [inline src/main/java/net/jcm/vsch/blocks/custom/DragInducerBlock.java:122]: These modes don't even do anything, we can probably remove them. But thanks for the fix.

File: src/main/java/net/jcm/vsch/blocks/custom/template/AbstractThrusterBlock.java [hunk 3]
```diff
@@ -0,0 +1,192 @@
...
+import net.minecraft.world.level.block.state.BlockState;
+import net.minecraft.world.level.block.state.StateDefinition;
+import net.minecraft.world.level.block.state.properties.BlockStateProperties;
+import net.minecraft.world.level.block.state.properties.BooleanProperty;
+import net.minecraft.world.level.block.state.properties.EnumProperty;
+import net.minecraft.world.phys.BlockHitResult;
+import net.minecraft.world.phys.shapes.CollisionContext;
+import net.minecraft.world.phys.shapes.VoxelShape;
+
+public abstract class AbstractThrusterBlock<T extends AbstractThrusterBlockEntity> extends DirectionalBlock implements EntityBlock {
```
Comment (blockninja124) [inline src/main/java/net/jcm/vsch/blocks/custom/template/AbstractThrusterBlock.java:43]: Ah I knew there was a better way to setup the thruster classes, just never bothered to think about what would be best.

File: src/main/java/net/jcm/vsch/blocks/custom/template/AbstractThrusterBlock.java [hunk 4]
```diff
@@ -0,0 +1,192 @@
...
+				.setValue(MODE, ThrusterMode.valueOf(VSCHConfig.THRUSTER_MODE.get()));
+	}
+
+	// Attach block entity
+	@Override
+	public abstract T newBlockEntity(BlockPos pos, BlockState state);
+
+	@Override
+	public <U extends BlockEntity> BlockEntityTicker<U> getTicker(Level level, BlockState state, BlockEntityType<U> type) {
+		return level.isClientSide() ? ((level0, pos0, state0, be) -> ((AbstractThrusterBlockEntity) be).clientTick(level0, pos0, state0, (AbstractThrusterBlockEntity) be)) : ((level0, pos0, state0, be) -> ((AbstractThrusterBlockEntity) be).serverTick(level0, pos0, state0, (AbstractThrusterBlockEntity) be));
```
Comment (blockninja124) [inline src/main/java/net/jcm/vsch/blocks/custom/template/AbstractThrusterBlock.java:186]: Last time I setup a block entity ticker register like this, it randomly refused to work. Even though this _should_ work, have you made sure to test it?

File: src/main/java/net/jcm/vsch/blocks/entity/AbstractThrusterBlockEntity.java [hunk 5]
```diff
@@ -0,0 +1,247 @@
...
+	@Override
+	public CompoundTag getUpdateTag() {
+		CompoundTag data = super.getUpdateTag();
+		data.putFloat("Power", this.getPower());
+		return data;
+	}
+
+	@Override
+	public ClientboundBlockEntityDataPacket getUpdatePacket() {
+		return ClientboundBlockEntityDataPacket.create(this);
```
Comment (blockninja124) [inline src/main/java/net/jcm/vsch/blocks/entity/AbstractThrusterBlockEntity.java:146]: What is this for? 🤔

**Comment by zyxkad** [comment]
@blockninja124 It's ready now

File: src/main/java/net/jcm/vsch/event/AtmosphericCollision.java [hunk 6]
```diff
@@ -48,29 +47,25 @@ public static void atmosphericCollisionTick(ServerLevel level, LevelAccessor wor
...
 			// If our current dimension has atmo data (e.g. a space dimension attached)
-			if (atmo_data_map.contains(shipDim)) {
-
-				Tag dim_atmo_data = atmo_data_map.get(shipDim);
-
-				// TODO: Gson is bad bad performance change this soon please future me!!
-				com.google.gson.JsonObject atmospheric_data = new com.google.gson.Gson().fromJson(dim_atmo_data.getAsString(), com.google.gson.JsonObject.class);
+			if (atmoDatas.contains(shipDim)) {
 
+				CompoundTag atmoData = atmoDatas.getCompound(shipDim);
```
Comment (blockninja124) [inline src/main/java/net/jcm/vsch/event/AtmosphericCollision.java:58]: Ah thanks for replacing GSON.

File: src/main/java/net/jcm/vsch/mixin/MixinSpaceSuitLogic.java [hunk 7]
```diff
@@ -43,61 +43,53 @@ private static void execute(LevelAccessor world, Entity entity, CallbackInfoRetu
...
+				}
+
+				boolean isSpaceSuitItem = 
+					stack.getItem() instanceof SteelSuitItem ||
+					stack.getItem() instanceof TitaniumSuitItem ||
+					stack.getItem() instanceof NickelSuitItem ||
+					stack.getItem() instanceof MagnetBootItem;
+
+				// "Why is this entire mixin just for this one check?" you ask? :revenge~1: :clueless:
+				if (!isSpaceSuitItem) {
```
Comment (blockninja124) [inline src/main/java/net/jcm/vsch/mixin/MixinSpaceSuitLogic.java:82]: Hmm perhaps in the future we could turn this into an item tag, but for now this is good

File: src/main/java/net/jcm/vsch/ship/VSCHForceInducedShips.java [hunk 8]
```diff
@@ -28,22 +30,27 @@ public class VSCHForceInducedShips implements ShipForcesInducer {
...
+
+	public VSCHForceInducedShips() {}
+
+	public VSCHForceInducedShips(String dimensionId) {
+		this.dimensionId = dimensionId;
+	}
 
 	@Override
 	public void applyForces(@NotNull PhysShip physicShip) {
-		var physShip = (PhysShipImpl) physicShip;
```
Comment (blockninja124) [inline src/main/java/net/jcm/vsch/ship/VSCHForceInducedShips.java:43]: Accidental kotlin? xD

File: src/main/java/net/jcm/vsch/ship/VSCHForceInducedShips.java [hunk 9]
```diff
@@ -211,12 +214,13 @@ public static VSCHForceInducedShips getOrCreate(ServerShip ship) {
 	}
 
 	public static VSCHForceInducedShips get(Level level, BlockPos pos) {
+		ServerLevel serverLevel = (ServerLevel) level;
 		// Don't ask, I don't know
-		ServerShip ship = (ServerShip) ((VSGameUtilsKt.getShipObjectManagingPos(level, pos) != null) ? VSGameUtilsKt.getShipObjectManagingPos(level, pos) : VSGameUtilsKt.getShipManagingPos(level, pos));
```
Comment (blockninja124) [inline src/main/java/net/jcm/vsch/ship/VSCHForceInducedShips.java:215]: I mostly copied this line from tournament, and didn't bother trying to simplify it. Are you sure your simple version is an equivalent? If so, cool. Just want to make sure we don't break this code.

File: src/main/java/net/jcm/vsch/util/TeleportUtils.java [hunk 10]
```diff
@@ -208,21 +206,18 @@ public static HashMap<Entity, Vec3> calculateOffsets(ServerLevel level, AABB aab
...
-            if (entity instanceof ServerPlayer) {
-
-                Vec3 shipOffset = entityOffsets.get(entity);
+            if (entity instanceof ServerPlayer player) {
+                Vec3 shipOffset = entityOffsets.get(player);
                 Vec3 newPosition = center.add(shipOffset);
 
                 // Players need a different teleport command to entities
-                ((ServerPlayer) entity).teleportTo(newLevel, newPosition.x, newPosition.y, newPosition.z, entity.getYRot(), entity.getXRot());
+                player.teleportTo(newLevel, newPosition.x, newPosition.y, newPosition.z, player.getYRot(), player.getXRot());
```
Comment (blockninja124) [inline src/main/java/net/jcm/vsch/util/TeleportUtils.java:220]: Are you sure this is fine? I feel like I remember Entity and Player have the same "teleportTo" method but players would freak out of the Entity method was used on them.

**Review by blockninja124 — APPROVED** [review]
This is quite an impressive PR, thanks!

File: src/main/java/net/jcm/vsch/blocks/custom/template/AbstractThrusterBlock.java (hunk 4 above)
Comment (zyxkad) [reply src/main/java/net/jcm/vsch/blocks/custom/template/AbstractThrusterBlock.java:186]: I tested all three thrusters and they works fine? maybe you had missed something?

Comment (blockninja124) [reply src/main/java/net/jcm/vsch/blocks/custom/template/AbstractThrusterBlock.java:186]: Probably 🤷

File: src/main/java/net/jcm/vsch/blocks/entity/AbstractThrusterBlockEntity.java (hunk 5 above)
Comment (blockninja124) [reply src/main/java/net/jcm/vsch/blocks/entity/AbstractThrusterBlockEntity.java:146]: But why does the client need to know what power level they have?

File: src/main/java/net/jcm/vsch/ship/VSCHForceInducedShips.java (hunk 9 above)
Comment (zyxkad) [reply src/main/java/net/jcm/vsch/ship/VSCHForceInducedShips.java:215]: Myself also do not know what's the difference between `getShipObjectManagingPos` and `getShipManagingPos`... but the simplify version technically should give the same result.

File: src/main/java/net/jcm/vsch/util/TeleportUtils.java (hunk 10 above)
Comment (zyxkad) [reply src/main/java/net/jcm/vsch/util/TeleportUtils.java:220]: They are equivalent but I just put the type casting above in the `if instaceof`

File: src/main/java/net/jcm/vsch/blocks/entity/AbstractThrusterBlockEntity.java (hunk 5 above)
Comment (zyxkad) [reply src/main/java/net/jcm/vsch/blocks/entity/AbstractThrusterBlockEntity.java:146]: Because you want dynamic particles :)

File: src/main/java/net/jcm/vsch/util/TeleportUtils.java (hunk 10 above)
Comment (jcm236) [reply src/main/java/net/jcm/vsch/util/TeleportUtils.java:220]:
```java
instanceof ServerPlayer player
```
does the typecasting automatically

Comment (zyxkad) [reply src/main/java/net/jcm/vsch/util/TeleportUtils.java:220]: yes

File: src/main/java/net/jcm/vsch/blocks/entity/AbstractThrusterBlockEntity.java (hunk 5 above)
Comment (blockninja124) [reply src/main/java/net/jcm/vsch/blocks/entity/AbstractThrusterBlockEntity.java:146]: Ohhhhh right, the particles need to be client side

Comment (jcm236) [reply src/main/java/net/jcm/vsch/blocks/entity/AbstractThrusterBlockEntity.java:146]: fair enough

File: src/main/java/net/jcm/vsch/util/TeleportUtils.java (hunk 10 above)
Comment (blockninja124) [reply src/main/java/net/jcm/vsch/util/TeleportUtils.java:220]: Ah I see, I missed that sorry.
